#!/usr/bin/env bash
# setup_automation.sh — Install cron jobs for vault maintenance.
#
# What it sets up:
#   1. Auto-reindex every 30 min (catches Obsidian edits)
#   2. Git auto-commit + push every hour (backup) — only if remote set
#   3. Daily compile of raw logs → memos at 18:00
#   4. Model warm-up at login (eliminates cold start)
#
# Design:
#   Cron lines do NOT interpolate $VAULT_PATH. Instead this script
#   writes small shim scripts under ~/.memo/ that source ~/.memo/cron.env
#   (PATH, API keys, MEMO_VAULT_PATH) and run the real work. Cron lines
#   are short, single-quoted, and use a sentinel marker for idempotent
#   re-runs.
#
# Usage: bash setup_automation.sh ~/memo-vault

set -euo pipefail

VAULT_PATH="${1:-$HOME/memo-vault}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ─── Safety: validate VAULT_PATH before embedding into any file ───
#
# Cron, shell, and shim scripts all parse paths. Reject anything that
# could break parsing or inject shell metacharacters. Allowlist: letters,
# digits, _ . / - and space. Reject newlines, $, backticks, quotes.
case "$VAULT_PATH" in
    "" )
        echo "ERROR: VAULT_PATH is empty" >&2; exit 1 ;;
    *[$'\n\r']* )
        echo "ERROR: VAULT_PATH contains newline — refusing" >&2; exit 1 ;;
    *[\$\"\'\`\\]* )
        echo "ERROR: VAULT_PATH contains shell metacharacters (\$, quote, backtick, backslash)" >&2; exit 1 ;;
esac
case "$VAULT_PATH" in
    *[!A-Za-z0-9_./\ -]* )
        echo "ERROR: VAULT_PATH contains characters outside [A-Za-z0-9_./ -]" >&2; exit 1 ;;
esac

# Resolve full paths so cron (minimal PATH) can find tools
PYTHON3="$(command -v python3 || true)"
if [ -z "$PYTHON3" ]; then
    echo "ERROR: python3 not found in PATH" >&2; exit 1
fi

# Resolve per-vault cache dir (~/.cache/memo/<hash>/) — keeps shims,
# env, and logs per-vault so two vaults on the same machine don't
# overwrite each other's cron config.
MEMO_DIR="$(python3 -c "
import sys
sys.path.insert(0, '$SCRIPT_DIR')
from memo_utils import get_memo_dir
print(get_memo_dir('$VAULT_PATH'))
")"
mkdir -p "$MEMO_DIR"
chmod 700 "$MEMO_DIR"

CRON_ENV="$MEMO_DIR/cron.env"
GIT_SHIM="$MEMO_DIR/git-sync.sh"
REINDEX_SHIM="$MEMO_DIR/reindex.sh"
COMPILE_SHIM="$MEMO_DIR/compile.sh"

CRON_MARKER="# MEMO_VAULT_AUTOMATION"

echo "═══════════════════════════════════════════════"
echo "  Setting up vault automation"
echo "  Vault:  $VAULT_PATH"
echo "  Python: $PYTHON3"
echo "  Shims:  $MEMO_DIR"
echo "═══════════════════════════════════════════════"

# ─── 0. Write cron.env (API keys + PATH + vault path) ───
#
# Cron does NOT source ~/.zshrc. Without this, OPENROUTER_API_KEY /
# ANTHROPIC_API_KEY are undefined, call_llm returns None, and
# compile_logs silently no-ops every day. We capture whatever's
# defined in the shell that ran setup_automation, so the user runs
# this script from an interactive shell where their keys are set.

write_env_var() {
    local name="$1"
    local value="${!name:-}"
    if [ -n "$value" ]; then
        # Single-quote to avoid expansion; escape single quotes inside value
        # by closing-reopening: 'foo'"'"'bar'
        local escaped
        escaped=$(printf '%s' "$value" | sed "s/'/'\"'\"'/g")
        echo "export $name='$escaped'"
    fi
}

{
    echo "# Generated by setup_automation.sh — do not edit by hand"
    echo "# Sourced by ~/.memo/*.sh shims at cron run time"
    echo "export PATH=\"/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin\""
    echo "export MEMO_VAULT_PATH=\"$VAULT_PATH\""
    write_env_var OPENROUTER_API_KEY
    write_env_var ANTHROPIC_API_KEY
    write_env_var MEMO_API_PROVIDER
    write_env_var MEMO_API_KEY
    write_env_var MEMO_MODEL
    write_env_var MEMO_API_URL
} > "$CRON_ENV"
chmod 600 "$CRON_ENV"
echo "  ✓ cron.env written ($CRON_ENV, mode 600)"

# ─── 1. Reindex shim ───

cat > "$REINDEX_SHIM" <<'SHIM'
#!/usr/bin/env bash
# Generated by setup_automation.sh
set -euo pipefail
ENV_FILE="$HOME/.memo/cron.env"
[ -r "$ENV_FILE" ] && . "$ENV_FILE"
exec python3 SCRIPT_DIR_PLACEHOLDER/memo_engine.py reindex --vault "$MEMO_VAULT_PATH" --incremental
SHIM
# Inject SCRIPT_DIR via sed (single-quoted heredoc preserved everything else)
sed -i.tmp "s|SCRIPT_DIR_PLACEHOLDER|$SCRIPT_DIR|" "$REINDEX_SHIM" && rm -f "$REINDEX_SHIM.tmp"
chmod 755 "$REINDEX_SHIM"

# ─── 2. Compile shim ───

cat > "$COMPILE_SHIM" <<'SHIM'
#!/usr/bin/env bash
# Generated by setup_automation.sh
set -euo pipefail
ENV_FILE="$HOME/.memo/cron.env"
[ -r "$ENV_FILE" ] && . "$ENV_FILE"
exec python3 SCRIPT_DIR_PLACEHOLDER/compile_logs.py --vault "$MEMO_VAULT_PATH"
SHIM
sed -i.tmp "s|SCRIPT_DIR_PLACEHOLDER|$SCRIPT_DIR|" "$COMPILE_SHIM" && rm -f "$COMPILE_SHIM.tmp"
chmod 755 "$COMPILE_SHIM"

# ─── 3. Git sync shim ───

cat > "$GIT_SHIM" <<'SHIM'
#!/usr/bin/env bash
# Generated by setup_automation.sh
set -euo pipefail
ENV_FILE="$HOME/.memo/cron.env"
[ -r "$ENV_FILE" ] && . "$ENV_FILE"

# Serialize git operations across overlapping cron runs.
LOCK="/tmp/memo-git-sync.lock"
exec 9>"$LOCK"
if ! flock -n 9; then
    echo "[$(date '+%F %T')] another git-sync is running — skipping" >&2
    exit 0
fi

cd "$MEMO_VAULT_PATH"
git add -A
if git diff --cached --quiet; then
    exit 0
fi
git commit -q -m "auto: vault sync $(date '+%Y-%m-%d %H:%M')"
git push -q origin main
SHIM
chmod 755 "$GIT_SHIM"

echo "  ✓ shim scripts written"

# ─── 4. Install cron entries idempotently using sentinel marker ───

install_cron_line() {
    local sentinel="$1"
    local line="$2"
    if crontab -l 2>/dev/null | grep -qF "$sentinel"; then
        echo "  ✓ cron entry [$sentinel] already installed"
    else
        (crontab -l 2>/dev/null; echo "$sentinel"; echo "$line") | crontab -
        echo "  ✓ cron entry [$sentinel] installed"
    fi
}

REINDEX_LOG="$MEMO_DIR/reindex.log"
COMPILE_LOG="$MEMO_DIR/compile.log"
GIT_LOG="$MEMO_DIR/git-sync.log"

install_cron_line "$CRON_MARKER reindex" "*/30 * * * * $REINDEX_SHIM >> $REINDEX_LOG 2>&1"
install_cron_line "$CRON_MARKER compile" "0 18 * * * $COMPILE_SHIM >> $COMPILE_LOG 2>&1"

# Git sync only if remote is configured.
if (cd "$VAULT_PATH" && git remote get-url origin >/dev/null 2>&1); then
    install_cron_line "$CRON_MARKER gitsync" "0 * * * * $GIT_SHIM >> $GIT_LOG 2>&1"
else
    echo "  ⚠ No git remote configured for $VAULT_PATH. Skipping git-sync cron."
    echo "    Enable later via: cd \"$VAULT_PATH\" && git remote add origin <url> && bash $0 \"$VAULT_PATH\""
fi

# ─── 5. Model warm-up at login (interactive shell only) ───

WARMUP_MARK="# Memo vault: pre-load embedding model"
WARMUP_CMD="(python3 $SCRIPT_DIR/memo_engine.py warm-up > /dev/null 2>&1 &)"

# Detect shell config file
if [ -f "$HOME/.zshrc" ]; then
    SHELL_RC="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then
    SHELL_RC="$HOME/.bashrc"
else
    SHELL_RC=""
fi

if [ -n "$SHELL_RC" ]; then
    if grep -qF "memo_engine.py warm-up" "$SHELL_RC" 2>/dev/null; then
        echo "  ✓ Model warm-up already in $SHELL_RC"
    else
        {
            printf "\n"
            printf "%s\n" "$WARMUP_MARK"
            printf "%s\n" "$WARMUP_CMD"
        } >> "$SHELL_RC"
        echo "  ✓ Model warm-up added to $SHELL_RC"
    fi

    if grep -qF "MEMO_VAULT_PATH" "$SHELL_RC" 2>/dev/null; then
        echo "  ✓ MEMO_VAULT_PATH already set in $SHELL_RC"
    else
        printf 'export MEMO_VAULT_PATH="%s"\n' "$VAULT_PATH" >> "$SHELL_RC"
        echo "  ✓ MEMO_VAULT_PATH added to $SHELL_RC"
    fi
fi

echo ""
echo "═══════════════════════════════════════════════"
echo "  Automation ready!"
echo ""
echo "  Cron jobs:     crontab -l"
echo "  Cron env:      $CRON_ENV"
echo "  Cache dir:     $MEMO_DIR"
echo "  Reindex log:   $REINDEX_LOG"
echo "  Compile log:   $COMPILE_LOG"
echo "  Git sync log:  $GIT_LOG"
echo "  Auto-memo log: $MEMO_DIR/auto_memo.log"
echo "═══════════════════════════════════════════════"
